// <auto-generated />
using System;
using DigiAlert.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigiAlert.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907210055_AddIsReadField")]
    partial class AddIsReadField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigiAlert.Api.Models.Contact", b =>
                {
                    b.Property<Guid>("IdContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_contact");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("IdContact");

                    b.HasIndex("IdUser");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.Event", b =>
                {
                    b.Property<Guid>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_event");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_datetime");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("IdEvent");

                    b.HasIndex("IdUser");

                    b.ToTable("events");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.EventParticipant", b =>
                {
                    b.Property<Guid>("IdEvent")
                        .HasColumnType("uuid")
                        .HasColumnName("id_event");

                    b.Property<Guid>("IdContact")
                        .HasColumnType("uuid")
                        .HasColumnName("id_contact");

                    b.HasKey("IdEvent", "IdContact");

                    b.HasIndex("IdContact");

                    b.ToTable("event_participants");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.Reminder", b =>
                {
                    b.Property<Guid>("IdReminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_reminder");

                    b.Property<string>("ApiResponse")
                        .HasColumnType("text")
                        .HasColumnName("api_response");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid>("IdContact")
                        .HasColumnType("uuid")
                        .HasColumnName("id_contact");

                    b.Property<Guid>("IdEvent")
                        .HasColumnType("uuid")
                        .HasColumnName("id_event");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("REMINDER")
                        .HasColumnName("purpose");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("IdReminder");

                    b.HasIndex("IdContact");

                    b.HasIndex("IdEvent");

                    b.ToTable("reminders");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.SmsTemplate", b =>
                {
                    b.Property<Guid>("IdTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_template");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_content");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_name");

                    b.HasKey("IdTemplate");

                    b.HasIndex("IdUser");

                    b.ToTable("sms_templates");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailApiKey")
                        .HasColumnType("text")
                        .HasColumnName("email_api_key");

                    b.Property<string>("EmailSender")
                        .HasColumnType("text")
                        .HasColumnName("email_sender");

                    b.Property<Guid>("KioskToken")
                        .HasColumnType("uuid")
                        .HasColumnName("kiosk_token");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_token_expires");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SenderId")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("sender_id");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.Contact", b =>
                {
                    b.HasOne("DigiAlert.Api.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.Event", b =>
                {
                    b.HasOne("DigiAlert.Api.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.EventParticipant", b =>
                {
                    b.HasOne("DigiAlert.Api.Models.Contact", "Contact")
                        .WithMany("EventParticipants")
                        .HasForeignKey("IdContact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiAlert.Api.Models.Event", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.Reminder", b =>
                {
                    b.HasOne("DigiAlert.Api.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("IdContact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiAlert.Api.Models.Event", "Event")
                        .WithMany("Reminders")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.SmsTemplate", b =>
                {
                    b.HasOne("DigiAlert.Api.Models.User", "User")
                        .WithMany("SmsTemplates")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.Contact", b =>
                {
                    b.Navigation("EventParticipants");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.Event", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("DigiAlert.Api.Models.User", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Events");

                    b.Navigation("SmsTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
